prof: &prof {type: http, size-limit: 15000, interval: 10800, health-check: {enable: true, url: http://connectivitycheck.gstatic.com/generate_204, interval: 300}}
      
global-client-fingerprint: random
log-level: silent
routing-mark: 6666
mode: rule
port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7893
ipv6: true
allow-lan: true
unified-delay: true
tcp-concurrent: true
interface-name: en0
profile:
  store-selected: false
  store-fake-ip: true
geodata-mode: true
dns:
  enable: true
  prefer-h3: false
  use-hosts: true
  use-system-hosts: true
  respect-rules: true
  listen: 0.0.0.0:53
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fallback: [ 'system', 1.1.1.1, 1.0.0.1, 8.8.8.8, 8.8.4.4 ]
  proxy-server-nameserver: [ 'system', 1.1.1.1, 1.0.0.1, 8.8.8.8, 8.8.4.4 ]
proxy-groups:
    - name: UMUM
      proxies: [ AUTO ]
      include-all-providers: true
      exclude-filter: UDP
      type: select
      lazy: true
    - name: UDP
      proxies: [ Server UDP, PASS ]
      use: [ udp ]
      type: select
      lazy: true
    - name: porn
      proxies: [ REJECT, PASS ]
      type: select
      lazy: true
    - name: IKLANWEB
      proxies: [ REJECT, PASS ]
      type: select
      lazy: true
    - interval: 600
      tolerance: 100
      name: Server UDP
      use: [ udp ]
      type: url-test
      url: 'http://connectivitycheck.gstatic.com/generate_204'
    - name: AUTO
      include-all-providers: true
      exclude-filter: UDP
      type: url-test
      url: 'http://connectivitycheck.gstatic.com/generate_204'
      interval: 600
      lazy: true
proxy-providers:
  'umum ntls':
    url: >-
      https://prod-test.jdevcloud.com/api/vless?cc=sg&cdn=true&tls=false&bug=bug&limit=3&format=vless&subdomain=bakrie.ac.id
    path: ./ntls
    override: {skip-cert-verify: true, packet-encoding: xudp, network: tcp, smux: {enabled: true}, additional-prefix: 'umum ntls '}
    <<: *prof
  'umum tls':
    url: >-
      https://prod-test.jdevcloud.com/api/vless?cc=sg&cdn=true&tls=true&bug=bug&limit=3&format=vless&subdomain=bakrie.ac.id
    path: ./tls
    override: {skip-cert-verify: true, packet-encoding: xudp, network: tcp, smux: {enabled: true}, additional-prefix: 'umum tls '}
    <<: *prof
  'akun':
    type: file
    path: "./AKUN"
    override: {skip-cert-verify: true, packet-encoding: xudp, network: tcp, smux: {enabled: true}, additional-prefix: 'x-akun '}
    health-check:
      enable: true
      url: http://connectivitycheck.gstatic.com/generate_204
      interval: 300
  'udp':
    url: >-
      https://raw.githubusercontent.com/absurd100/test/refs/heads/main/UDP-bug.yaml
    path: ./UDP
    override: {skip-cert-verify: true, packet-encoding: xudp, network: tcp, smux: {enabled: true}, additional-prefix: 'UDP '}
    <<: *prof

rule-providers:
  malware: 
    type: http 
    format: text 
    behavior: domain 
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/malware.txt" 
    path: ./ruleset/malware.txt
    interval: 86400
  phishing: 
    type: http 
    format: text 
    behavior: domain 
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/phishing.txt" 
    path: ./ruleset/phishing.txt 
    interval: 86400
rules:
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,122.122.0.0/8,DIRECT,no-resolve
- RULE-SET,phishing,REJECT
- RULE-SET,malware,REJECT
- NETWORK,UDP,UDP
- GEOSITE,category-porn,porn
- DST-PORT,123/136/137-139,DIRECT 
- SRC-PORT,123/136/137-139,DIRECT,udp
- AND,((NETWORK,UDP),(OR,((DST-PORT,443/80),(GEOSITE,youtube)))),REJECT
- AND,((OR,((DOMAIN-KEYWORD,instagram),(DOMAIN-KEYWORD,facebook))),(NETWORK,UDP)),REJECT
- AND,((GEOSITE,category-ads-all),(NOT,((DOMAIN-SUFFIX,googlesyndication.com)))),IKLANWEB
- MATCH,UMUM
